### ISSUE TITLE
HomePage

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#63]
_不是 issue 的待辦事項，就是這張票要完成的內容_

# HomePage:

- Header : #69 
- [x] HomePageBody
- Footer : #70

## HomePageBody:

- [x] HeroSection
- [x] #64
- [x] #65
- [x] #66
- [x] #67
- [x] #68

---

[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=893-28714&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
https://github.com/user-attachments/assets/6494905c-3b22-462e-8b17-dd5789ab79a3

<img src="https://github.com/user-attachments/assets/6494905c-3b22-462e-8b17-dd5789ab79a3" width=300 />

**Comment by Julian0701** [comment]
- take 1 hr, done
