### ISSUE TITLE
HomePage - WelcomeSection (Welcome to iSunCoin)

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#64]
- **White Paper** 按鈕可以點擊，要跟 Luphia 拿路徑

[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=896-33317&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
![Image](https://github.com/user-attachments/assets/ddc0adcf-549c-482e-8b9e-3a046b96c6a9)
![Image](https://github.com/user-attachments/assets/a8e7e2eb-ada6-4f58-9430-c0cff4f077dd)

**Comment by godmmt** [comment]
White Paper 白屁書：

[isuncoin_whitepaper_zh_v1.1.2.pdf](https://github.com/user-attachments/files/16537060/isuncoin_whitepaper_zh_v1.1.2.pdf)
[isuncoin_whitepaper_en_v1.1.2.pdf](https://github.com/user-attachments/files/16537061/isuncoin_whitepaper_en_v1.1.2.pdf)
[isuncoin_whitepaper_cn_v1.1.2.pdf](https://github.com/user-attachments/files/16537062/isuncoin_whitepaper_cn_v1.1.2.pdf)

**Comment by Julian0701** [comment]
- take 3 hrs, done
