### ISSUE TITLE
HomePage - ParticipateSection (Participate in iSunCoin)

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#65]
- download links 目前都還沒有

[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=906-24555&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
![Image](https://github.com/user-attachments/assets/7fb489b9-cdfb-49b3-bb0e-0f7dd5385dc4)

**Comment by Julian0701** [comment]
- take 3 hrs, done

**Comment by Julian0701** [comment]
- take 2 hrs, done
