### ISSUE TITLE
HomePage - RealTimeData

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#66]
[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=893-27240&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
![Image](https://github.com/user-attachments/assets/0ea43130-ddc6-45b3-b147-b8bbf42e3e06)

![Image](https://github.com/user-attachments/assets/9ef32211-412e-41bc-a3e1-36e8931c2f48)

**Comment by Julian0701** [comment]
- take 8 hrs, done

- 有空再回頭調整樣式
- [Proportional symbol map](https://www.react-simple-maps.io/examples/proportional-symbol-map/)
- [Mapchart with tooltip](https://www.react-simple-maps.io/examples/map-chart-with-tooltip/)
