### ISSUE TITLE
HomePage - ContactForm

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#68]
ContactForm
![截圖 2024-08-09 上午9 45 25](https://github.com/user-attachments/assets/fe00f090-66b7-42f4-bca1-98f3ed98476e)

**Comment by godmmt** [comment]
![Image](https://github.com/user-attachments/assets/92e44493-f9dd-4fe2-8fa1-e6541e7223b7)
![Image](https://github.com/user-attachments/assets/1f2f7d76-e517-4327-864b-6d8bcce2f5d1)

![Image](https://github.com/user-attachments/assets/8f1cf79b-7e16-4479-b525-cfc51b42f57e)
![Image](https://github.com/user-attachments/assets/410d5a5a-c835-472c-9095-a229167fde51)

**Comment by Julian0701** [comment]
- take 8 hrs, remain 3 hrs
- 由於 OAuth2.0 還在研究中，暫緩並先做其他 issue

**Comment by Julian0701** [comment]
- email API 已由 Luphia 協助完成 
- #111 
- done
