### ISSUE TITLE
DevelopPage

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#74]
_不是 issue 的待辦事項，就是這張票要完成的內容_

# DevelopPage:

- Header : #69 
- [x] DevelopPageBody
- Footer : #70

## DevelopPageBody:

- [x] #75
- [x] #76
- [x] #77
- [x] #67

---

[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=1028-19730&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
# Develop 分成 兩種期間

1. 投票期間
2. 提案期間

提案期間就不可以投票，投票期間不可以提案。

Current Proposals: 會根據提案數量延伸高度

Update History: 類似一種部落格，由後端傳來一期一期的部落格文章，文章內容是後端給的


https://github.com/user-attachments/assets/fdbbed3c-92ad-4046-8962-df0b94b4d294

<img src="https://github.com/user-attachments/assets/fdbbed3c-92ad-4046-8962-df0b94b4d294" width=300 />

**Comment by godmmt** [comment]
<details>

<summary> Modal & Toast 👇
</summary>

![image](https://github.com/user-attachments/assets/8bc658ff-c77d-429e-94f5-c4b417c4cc69)
</details>

**Comment by Julian0701** [comment]
- take 2 hrs, done
