### ISSUE TITLE
DevelopPage - CurrentProposals

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#75]
[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=1009-38211&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
![vote](https://github.com/user-attachments/assets/91b026d6-075b-4c01-937c-cbccbfa52d5a)

**Comment by Julian0701** [comment]
- take 3 hrs, done
