### ISSUE TITLE
DevelopPage - ProposeForm (I want to propose)

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#76]
[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=1028-20102&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
![propose](https://github.com/user-attachments/assets/4588060c-6126-4370-b23e-4d6c644d34a1)

**Comment by godmmt** [comment]
![propose (1)](https://github.com/user-attachments/assets/96e62f9c-e6e4-441f-85d2-0f1613ff62cf)

**Comment by Julian0701** [comment]
- take 3 hrs, done
