### ISSUE TITLE
DevelopPage - UpdateHistory

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/iSunCoin-official#77]
# UpdateHistory:

- [x] UpdateHistoryItem
- [x] Pagination
- [x] DatePicker

---

[Mockup](https://www.figma.com/design/WMLBd54cxAo92xuA2Jw51v/iSunCoin-Landing-Page?node-id=1033-35275&t=CHZXRiOs6z3owA1J-4)

**Comment by godmmt** [comment]
![Frame 80](https://github.com/user-attachments/assets/d2bdc023-82e0-4121-8ea9-1f09b2317908)

**Comment by Julian0701** [comment]
- take 8 hrs, done
